---
name: snapcast-server
version: "0.1"
slug: snapcastserver
description: Snapcast Server
startup: system
boot: auto
init: false
map:
  - share:rw
options:
  # Input streams
  streams:
    - tcp://0.0.0.0?port=4953&name=snapbroadcast

  # Stream settings
  stream_buffer_size: 1000
  stream_codec: flac
  stream_sampleformat: "48000:16:2"
  send_to_muted: false

  # HTTP settings
  http_enabled: true
  http_doc_root: ""

  # TCP settings
  tcp_enabled: true

  # Logging settings
  logging_enabled: true

  # Server settings
  server_threads: "-1"
  server_datadir: "/share/snapcast/"
schema:
  # Input streams
  streams:
    - str

  # Stream settings
  stream_buffer_size: int
  stream_codec: str
  stream_sampleformat: str
  send_to_muted: str

  # HTTP settings
  http_enabled: bool
  http_doc_root: str

  # TCP settings
  tcp_enabled: bool

  # Logging settings
  logging_enabled: bool

  # Server settings
  server_threads: int
  server_datadir: str
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  4953/tcp: 4953
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
