name: snapcast_client
version: "0.1"
slug: snapcast_client
description: Snapcast client
url: https://github.com/cr7pt0gr4ph7/homeassistant-addons-snapcast/tree/main/snapclient
startup: services
boot: auto
init: false
audio: true
options:
  url: tcp://snapcastserver
schema:
  url: str

  # Client settings
  host_id: str?
  instance_id: str?

  # Card settings
  card: str?
  latency: int?
  player: str?
  mixer: str?

  # Logging settings
  logging_enabled: bool?
  logging_level: str?

  # Custom CLI options
  additional_args: str?
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
